### ISSUE TITLE
As a system administrator, I want to maintain reference values for system types

### ISSUE THREAD

**Issue by gjemiolo-git** [Software-Engineering-Red/MAUI-APP#10]

**Comment by Emesaye** [comment]
**End user goal:**
* _To be able to list, create, update and delete reference values for system types_

**End business goal:**
* _To have appropriate system types available_ 

**Acceptance criteria:**

* _A system type item data ( Windows, iOS, Linux etc.) can be created, viewed, updated and deleted (CRUD functionality)_

**Measurement of success:**

* _Unit tests pass for all CRUD operations_

**Notes:**

*  _The database table will be called_ `system_type`
*  _The table will have a single column_ `name`

**Comment by Emesaye** [comment]
Created System Types UI to store and CRUD(create, read ,update and delete)  the data. Tested for PR. Awaiting review/feedback.
