### ISSUE TITLE
As a system administrator, I want to maintain reference values for position statuses

### ISSUE THREAD

**Issue by gjemiolo-git** [Software-Engineering-Red/MAUI-APP#16]
End user goal: To be able to list, create, update and delete reference values for position statuses

End business goal: To have appropriate position statuses available to describe a person's position in an organisation (e.g. 'active', 'retired', 'seconded out')

Acceptance criteria:

A position status item can be created, viewed, updated and deleted (CRUD functionality)
Measurement of success:

Unit tests pass for all CRUD operations
Notes:

The database table will be called position_status
The table will have a single column, name

**Comment by justinwylie033** [comment]
Completed it mate. Confirm Pull Request.
