### ISSUE TITLE
As a system administrator, I want to maintain reference values for roles

### ISSUE THREAD

**Issue by gjemiolo-git** [Software-Engineering-Red/MAUI-APP#17]
End user goal:
To be able to list, create, update and delete reference values for roles

End business goal:
To have appropriate role records available to assign to users (e.g. Team Leader, Deputy Team Leader, Team Support and Logistics Manager, etc)

Acceptance criteria:

A role item can be created, viewed, updated and deleted (CRUD functionality)
Measurement of success:

Unit tests pass for all CRUD operations
Notes:

The database table will be called roles
The table will have a single column, name

**Comment by justinwylie033** [comment]
Completed it mate. Confirm Pull Request.
