### ISSUE TITLE
As a system administrator, I want to maintain reference values for room type

### ISSUE THREAD

**Issue by gjemiolo-git** [Software-Engineering-Red/MAUI-APP#7]

**Comment by calvin1337** [comment]
End user goal: To be able to list, create, update and delete reference values for room use types

End business goal: To have appropriate types available to describe a room use (e.g. 'accommodation', 'storage', 'kitchen', etc.)

Acceptance criteria:

A room use type item can be created, viewed, updated and deleted (CRUD functionality)
Measurement of success:

Unit tests pass for all CRUD operations
